# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-03-02 01:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20200212_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headline',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
